// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Saga struct {
	ID        string
	Workflow  string
	Status    string
	Context   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type SagaStep struct {
	ID         int64
	SagaID     string
	StepIndex  int32
	Name       string
	GrpcTarget string
	Status     string
	Attempt    int32
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Error      pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
