// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimNextStep(ctx context.Context, updatedAt pgtype.Timestamptz) (ClaimNextStepRow, error)
	CreateSaga(ctx context.Context, arg CreateSagaParams) error
	DeleteSagaStepsFromIndex(ctx context.Context, arg DeleteSagaStepsFromIndexParams) error
	GetSaga(ctx context.Context, id string) (Saga, error)
	GetSagaForUpdate(ctx context.Context, id string) (Saga, error)
	GetSagaSteps(ctx context.Context, sagaID string) ([]GetSagaStepsRow, error)
	GetSagaStepsForUpdate(ctx context.Context, sagaID string) ([]GetSagaStepsForUpdateRow, error)
	ListSagas(ctx context.Context, arg ListSagasParams) ([]Saga, error)
	ListSagasByStatus(ctx context.Context, arg ListSagasByStatusParams) ([]Saga, error)
	UpdateSaga(ctx context.Context, arg UpdateSagaParams) error
	UpsertSagaStep(ctx context.Context, arg UpsertSagaStepParams) error
}

var _ Querier = (*Queries)(nil)
