// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClaimNextStep(ctx context.Context, updatedAt pgtype.Timestamptz) (ClaimNextStepRow, error)
	CreateSaga(ctx context.Context, arg CreateSagaParams) error
	DeleteSagaSteps(ctx context.Context, sagaID string) error
	GetSaga(ctx context.Context, id string) (Saga, error)
	GetSagaForUpdate(ctx context.Context, id string) (Saga, error)
	GetSagaSteps(ctx context.Context, sagaID string) ([]GetSagaStepsRow, error)
	GetSagaStepsForUpdate(ctx context.Context, sagaID string) ([]GetSagaStepsForUpdateRow, error)
	InsertSagaStep(ctx context.Context, arg InsertSagaStepParams) error
	ListSagas(ctx context.Context, arg ListSagasParams) ([]Saga, error)
	ListSagasByStatus(ctx context.Context, arg ListSagasByStatusParams) ([]Saga, error)
	UpdateSaga(ctx context.Context, arg UpdateSagaParams) error
}

var _ Querier = (*Queries)(nil)
