// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sagas.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextStep = `-- name: ClaimNextStep :one
WITH candidate AS (
    SELECT ss.saga_id, ss.step_index
    FROM saga_steps ss
    INNER JOIN sagas s ON s.id = ss.saga_id
    WHERE s.status IN ('CREATED', 'RUNNING')
      AND (
        ss.status = 'PENDING'
        OR (ss.status = 'RUNNING' AND ss.updated_at <= $1)
      )
      AND NOT EXISTS (
        SELECT 1
        FROM saga_steps prev
        WHERE prev.saga_id = ss.saga_id
          AND prev.step_index < ss.step_index
          AND prev.status <> 'COMPLETED'
      )
    ORDER BY ss.updated_at ASC, ss.id ASC
    FOR UPDATE OF ss SKIP LOCKED
    LIMIT 1
)
UPDATE saga_steps ss
SET
    status = 'RUNNING',
    attempt = ss.attempt + 1,
    started_at = COALESCE(ss.started_at, NOW()),
    finished_at = NULL,
    error = NULL,
    updated_at = NOW()
FROM candidate
WHERE ss.saga_id = candidate.saga_id
  AND ss.step_index = candidate.step_index
RETURNING ss.saga_id, ss.step_index, ss.name, ss.attempt
`

type ClaimNextStepRow struct {
	SagaID    string
	StepIndex int32
	Name      string
	Attempt   int32
}

func (q *Queries) ClaimNextStep(ctx context.Context, updatedAt pgtype.Timestamptz) (ClaimNextStepRow, error) {
	row := q.db.QueryRow(ctx, claimNextStep, updatedAt)
	var i ClaimNextStepRow
	err := row.Scan(
		&i.SagaID,
		&i.StepIndex,
		&i.Name,
		&i.Attempt,
	)
	return i, err
}

const createSaga = `-- name: CreateSaga :exec
INSERT INTO sagas (id, workflow, status, context, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSagaParams struct {
	ID        string
	Workflow  string
	Status    string
	Context   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSaga(ctx context.Context, arg CreateSagaParams) error {
	_, err := q.db.Exec(ctx, createSaga,
		arg.ID,
		arg.Workflow,
		arg.Status,
		arg.Context,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteSagaSteps = `-- name: DeleteSagaSteps :exec
DELETE FROM saga_steps
WHERE saga_id = $1
`

func (q *Queries) DeleteSagaSteps(ctx context.Context, sagaID string) error {
	_, err := q.db.Exec(ctx, deleteSagaSteps, sagaID)
	return err
}

const getSaga = `-- name: GetSaga :one
SELECT id, workflow, status, context, created_at, updated_at
FROM sagas
WHERE id = $1
`

func (q *Queries) GetSaga(ctx context.Context, id string) (Saga, error) {
	row := q.db.QueryRow(ctx, getSaga, id)
	var i Saga
	err := row.Scan(
		&i.ID,
		&i.Workflow,
		&i.Status,
		&i.Context,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSagaForUpdate = `-- name: GetSagaForUpdate :one
SELECT id, workflow, status, context, created_at, updated_at
FROM sagas
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetSagaForUpdate(ctx context.Context, id string) (Saga, error) {
	row := q.db.QueryRow(ctx, getSagaForUpdate, id)
	var i Saga
	err := row.Scan(
		&i.ID,
		&i.Workflow,
		&i.Status,
		&i.Context,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSagaSteps = `-- name: GetSagaSteps :many
SELECT name, grpc_target, status, attempt, started_at, finished_at, error
FROM saga_steps
WHERE saga_id = $1
ORDER BY step_index ASC
`

type GetSagaStepsRow struct {
	Name       string
	GrpcTarget string
	Status     string
	Attempt    int32
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Error      pgtype.Text
}

func (q *Queries) GetSagaSteps(ctx context.Context, sagaID string) ([]GetSagaStepsRow, error) {
	rows, err := q.db.Query(ctx, getSagaSteps, sagaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSagaStepsRow
	for rows.Next() {
		var i GetSagaStepsRow
		if err := rows.Scan(
			&i.Name,
			&i.GrpcTarget,
			&i.Status,
			&i.Attempt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSagaStepsForUpdate = `-- name: GetSagaStepsForUpdate :many
SELECT name, grpc_target, status, attempt, started_at, finished_at, error
FROM saga_steps
WHERE saga_id = $1
ORDER BY step_index ASC
FOR UPDATE
`

type GetSagaStepsForUpdateRow struct {
	Name       string
	GrpcTarget string
	Status     string
	Attempt    int32
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Error      pgtype.Text
}

func (q *Queries) GetSagaStepsForUpdate(ctx context.Context, sagaID string) ([]GetSagaStepsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getSagaStepsForUpdate, sagaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSagaStepsForUpdateRow
	for rows.Next() {
		var i GetSagaStepsForUpdateRow
		if err := rows.Scan(
			&i.Name,
			&i.GrpcTarget,
			&i.Status,
			&i.Attempt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSagaStep = `-- name: InsertSagaStep :exec
INSERT INTO saga_steps (
    saga_id,
    step_index,
    name,
    grpc_target,
    status,
    attempt,
    started_at,
    finished_at,
    error,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW())
`

type InsertSagaStepParams struct {
	SagaID     string
	StepIndex  int32
	Name       string
	GrpcTarget string
	Status     string
	Attempt    int32
	StartedAt  pgtype.Timestamptz
	FinishedAt pgtype.Timestamptz
	Error      pgtype.Text
}

func (q *Queries) InsertSagaStep(ctx context.Context, arg InsertSagaStepParams) error {
	_, err := q.db.Exec(ctx, insertSagaStep,
		arg.SagaID,
		arg.StepIndex,
		arg.Name,
		arg.GrpcTarget,
		arg.Status,
		arg.Attempt,
		arg.StartedAt,
		arg.FinishedAt,
		arg.Error,
	)
	return err
}

const listSagas = `-- name: ListSagas :many
SELECT id, workflow, status, context, created_at, updated_at
FROM sagas
ORDER BY created_at ASC, id ASC
LIMIT $1 OFFSET $2
`

type ListSagasParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListSagas(ctx context.Context, arg ListSagasParams) ([]Saga, error) {
	rows, err := q.db.Query(ctx, listSagas, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Saga
	for rows.Next() {
		var i Saga
		if err := rows.Scan(
			&i.ID,
			&i.Workflow,
			&i.Status,
			&i.Context,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSagasByStatus = `-- name: ListSagasByStatus :many
SELECT id, workflow, status, context, created_at, updated_at
FROM sagas
WHERE status = $1
ORDER BY created_at ASC, id ASC
LIMIT $2 OFFSET $3
`

type ListSagasByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) ListSagasByStatus(ctx context.Context, arg ListSagasByStatusParams) ([]Saga, error) {
	rows, err := q.db.Query(ctx, listSagasByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Saga
	for rows.Next() {
		var i Saga
		if err := rows.Scan(
			&i.ID,
			&i.Workflow,
			&i.Status,
			&i.Context,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSaga = `-- name: UpdateSaga :exec
UPDATE sagas
SET workflow = $2,
    status = $3,
    context = $4,
    updated_at = $5
WHERE id = $1
`

type UpdateSagaParams struct {
	ID        string
	Workflow  string
	Status    string
	Context   []byte
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateSaga(ctx context.Context, arg UpdateSagaParams) error {
	_, err := q.db.Exec(ctx, updateSaga,
		arg.ID,
		arg.Workflow,
		arg.Status,
		arg.Context,
		arg.UpdatedAt,
	)
	return err
}
